services:
  fbc:
    build: .
    container_name: fbc
    volumes:
      # shorten letsencrypt path because symbolic link is not supported else where
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "7862:7862"
    restart: unless-stopped